name: Deploy to FTP

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP client
        run: sudo apt-get install -y lftp

      - name: Deploy to FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST <<EOF
          mirror -R ./local-directory /remote-directory
          bye
          EOF
